// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZz2wrpKiUMTiqjECovqo35oaRLEdYWBI',
    appId: '1:457770686590:web:d364f72884fc7377a4e02f',
    messagingSenderId: '457770686590',
    projectId: 'profile-5d517',
    authDomain: 'profile-5d517.firebaseapp.com',
    storageBucket: 'profile-5d517.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD98qFBTsVYYe_g3X6VT2IcUmmHlyNL0U',
    appId: '1:457770686590:android:ee876f435ba9b987a4e02f',
    messagingSenderId: '457770686590',
    projectId: 'profile-5d517',
    storageBucket: 'profile-5d517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMKKJNHbywhp64MX_wDnkirweoUbCghDw',
    appId: '1:457770686590:ios:f702362126290f32a4e02f',
    messagingSenderId: '457770686590',
    projectId: 'profile-5d517',
    storageBucket: 'profile-5d517.appspot.com',
    iosClientId: '457770686590-8m62gem42j184v67hvvof7kp55nt5ohn.apps.googleusercontent.com',
    iosBundleId: 'com.example.curriculum',
  );
}
